#!/usr/bin/env python3
"""
Helper script to actually store memories in MCP KB via API calls.

This script loads the memories generated by store_in_mcp_kb_v2.py
and stores them via MCP KB Memory API.
"""

import json
import sys
from pathlib import Path
from store_in_mcp_kb_v2 import EnhancedKBStorage


def store_memories_via_api(analysis_file: str) -> None:
    """Generate and return memories for MCP KB storage."""

    # Create storage handler
    storage = EnhancedKBStorage(analysis_file)

    # Generate all memories
    print(f"🎬 Generating memories for video: {storage.video_id}")
    memories = storage.generate_all_memories()

    print(f"✅ Generated {len(memories)} memories")
    print("\n📦 Memories to store:")

    for i, memory in enumerate(memories, 1):
        print(f"\n{i}. {memory['type']}")
        print(f"   - Content size: {len(memory['content'])} chars")
        print(f"   - Tags: {len(memory['tags'])} tags")
        print(f"   - First 100 chars: {memory['content'][:100]}...")

    # Return memories in a format that Claude Code can use
    output = {
        'video_id': storage.video_id,
        'total_memories': len(memories),
        'memories': memories
    }

    # Save to JSON for Claude Code to read
    output_file = Path("workspace/mcp_ready") / f"{storage.video_id}_memories.json"
    output_file.parent.mkdir(exist_ok=True)

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(output, f, indent=2)

    print(f"\n✅ Memories saved to: {output_file}")
    print(f"\n💡 Claude Code can now read this file and store via MCP KB API")

    return output


def main():
    """CLI entry point."""
    if len(sys.argv) < 2:
        print("Store Memories via API")
        print("\nUsage:")
        print("  python scripts/store_memories_api.py <analysis_json_file>")
        return

    analysis_file = sys.argv[1]

    if not Path(analysis_file).exists():
        print(f"❌ File not found: {analysis_file}")
        sys.exit(1)

    try:
        store_memories_via_api(analysis_file)
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
